name: Deploy to Github pages

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload bundle
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.upload.outputs.page_url }}
    steps:
      - name: Deploy to Github pages
        uses: actions/deploy-pages@v4